from datetime import date

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from authorizations.models import ReportValue, ReportingPeriod
from authorizations.reporting import ReportingConfigurationError, build_current_report_snapshot


QUARTER_END_DATES = {
    1: (3, 31),
    2: (6, 30),
    3: (9, 30),
    4: (12, 31),
}


def quarter_for_date(value):
    return ((value.month - 1) // 3) + 1


def quarter_end_date(year, quarter):
    try:
        month, day = QUARTER_END_DATES[quarter]
    except KeyError:
        raise CommandError('Quarter must be between 1 and 4.')
    return date(year, month, day)


def is_quarter_end(value):
    return (value.month, value.day) == QUARTER_END_DATES[quarter_for_date(value)]


class Command(BaseCommand):
    help = (
        'Generate and store one quarterly report snapshot from current authorization data. '
        'Existing quarterly reports are immutable unless --force is provided.'
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--year',
            type=int,
            help='Reporting year to generate. Must be provided with --quarter for manual generation.',
        )
        parser.add_argument(
            '--quarter',
            type=int,
            choices=[1, 2, 3, 4],
            help='Reporting quarter to generate. Must be provided with --year for manual generation.',
        )
        parser.add_argument(
            '--authorization-officer-name',
            default='Generated by authorization portal',
            help='Authorization officer name to store on the reporting period.',
        )
        parser.add_argument(
            '--force',
            action='store_true',
            help='Replace an existing stored report for the selected quarter.',
        )

    def handle(self, *args, **options):
        year = options['year']
        quarter = options['quarter']
        force = options['force']
        officer_name = options['authorization_officer_name'].strip()
        today = date.today()

        if bool(year) != bool(quarter):
            raise CommandError('--year and --quarter must be provided together.')
        if not officer_name:
            raise CommandError('--authorization-officer-name cannot be blank.')

        if year and quarter:
            as_of = quarter_end_date(year, quarter)
        else:
            if not is_quarter_end(today):
                self.stdout.write(
                    f'No report generated. {today.isoformat()} is not the last day of a quarter.'
                )
                return
            year = today.year
            quarter = quarter_for_date(today)
            as_of = today

        existing_period = ReportingPeriod.objects.filter(year=year, quarter=quarter).first()
        if existing_period and not force:
            raise CommandError(
                f'Q{quarter} {year} already has a stored report. '
                'Use --force only if you intentionally need to replace it.'
            )

        try:
            snapshot = build_current_report_snapshot(as_of=as_of)
        except ReportingConfigurationError as exc:
            raise CommandError('; '.join(exc.messages))

        with transaction.atomic():
            if existing_period:
                existing_period.authorization_officer_name = officer_name
                existing_period.save(update_fields=['authorization_officer_name', 'updated_at'])
                ReportValue.objects.filter(reporting_period=existing_period).delete()
                period = existing_period
            else:
                period = ReportingPeriod.objects.create(
                    year=year,
                    quarter=quarter,
                    authorization_officer_name=officer_name,
                )

            report_values = []
            for report_family, rows in snapshot.items():
                for row in rows:
                    report_values.append(
                        ReportValue(
                            reporting_period=period,
                            report_family=report_family,
                            region_name=row['region_name'],
                            subject_name=row['subject_name'],
                            metric_name=row['metric_name'],
                            value=row['value'],
                            display_order=row['display_order'],
                        )
                    )
            ReportValue.objects.bulk_create(report_values, batch_size=1000)

        action = 'Replaced' if existing_period else 'Generated'
        self.stdout.write(
            self.style.SUCCESS(
                f'{action} stored report for Q{quarter} {year} as of {as_of.isoformat()}.'
            )
        )
        self.stdout.write(f'Report values stored: {len(report_values)}')
