# Generated by Django 5.1.4 on 2025-04-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('Kingdom', 'Kingdom'), ('Principality', 'Principality'), ('Region', 'Region'), ('Barony', 'Barony'), ('Province', 'Province'), ('Shire', 'Shire'), ('Riding', 'Riding'), ('Canton', 'Canton'), ('College', 'College'), ('Stronghold', 'Stronghold'), ('Port', 'Port'), ('Incipient Shire', 'Incipient Shire'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
