# Generated by Django 5.1.4 on 2025-06-07 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0002_create_authorization_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='expiration',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='marshal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marshal', to='authorizations.person'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizations_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='sca_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='authorization',
            table=None,
        ),
    ]
