# Generated by Django 5.1.4 on 2025-04-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0002_branch_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('Ducal', 'Ducal'), ('County', 'County'), ('Viscounty', 'Viscounty'), ('Peerage', 'Peerage'), ('Baronial', 'Baronial'), ('Grant of Arms', 'Grant of Arms'), ('Award of Arms', 'Award of Arms'), ('Non-Armigerous', 'Non-Armigerous')], default='Non-Armigerous', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorizations.title'),
        ),
    ]
