# Generated by Django 5.1.4 on 2025-05-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0003_title_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
