# Generated by Django 5.2.7 on 2025-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0003_alter_authorization_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
