# Generated by Django 5.1.4 on 2025-05-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a 10 digit phone number', max_length=20, null=True),
        ),
    ]
