# Generated by Django 5.1.4 on 2025-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0006_alter_branch_region_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
