# Generated by Django 5.1.4 on 2026-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorizations', '0007_user_notes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'email'), name='unique_user_first_last_email'),
        ),
    ]
