# Generated by Django 5.1.4 on 2025-06-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0007_person_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_check_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signed_waiver',
            field=models.BooleanField(default=False),
        ),
    ]
