# Generated by Django 5.1.4 on 2026-02-07 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0008_user_unique_user_first_last_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_source_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
