# Generated by Django 5.1.4 on 2025-06-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0008_user_background_check_expiration_user_signed_waiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signed_waiver',
        ),
        migrations.AddField(
            model_name='user',
            name='signed_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
