# Generated by Django 5.1.4 on 2025-06-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0009_remove_user_signed_waiver_user_signed_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='signed_expiration',
            new_name='waiver_expiration',
        ),
    ]
