# Generated by Django 5.1.4 on 2026-02-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0009_user_merged_at_user_merged_into'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationPortalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_kao_verification', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_portal_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'authorization portal setting',
                'verbose_name_plural': 'authorization portal settings',
            },
        ),
    ]
