# Generated by Django 5.2.7 on 2026-02-20 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0010_authorizationportalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(9999)])),
                ('quarter', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('authorization_officer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reporting period',
                'verbose_name_plural': 'reporting periods',
                'ordering': ['-year', '-quarter'],
                'constraints': [models.UniqueConstraint(fields=('year', 'quarter'), name='unique_reporting_period_year_quarter')],
            },
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_family', models.CharField(choices=[('quarterly_marshal', 'Quarterly Marshal Report'), ('regional_breakdown', 'Regional Breakdown'), ('equestrian', 'Equestrian Report')], max_length=50)),
                ('region_name', models.CharField(blank=True, default='', max_length=150)),
                ('subject_name', models.CharField(max_length=150)),
                ('metric_name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_values', to='authorizations.reportingperiod')),
            ],
            options={
                'verbose_name': 'report value',
                'verbose_name_plural': 'report values',
                'ordering': ['report_family', 'region_name', 'display_order', 'subject_name', 'metric_name'],
                'indexes': [models.Index(fields=['report_family', 'region_name'], name='authorizati_report__0866cc_idx'), models.Index(fields=['reporting_period', 'report_family', 'display_order'], name='authorizati_reporti_fd3f56_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporting_period', 'report_family', 'region_name', 'subject_name', 'metric_name'), name='unique_report_value_for_period_dimension')],
            },
        ),
    ]
