# Generated by Django 5.2.7 on 2026-03-04 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0013_sanction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('membership_expiration', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'membership roster entry',
                'verbose_name_plural': 'membership roster entries',
                'indexes': [models.Index(fields=['membership_number', 'membership_expiration'], name='authorizati_membersh_75b202_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembershipRosterImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_roster_imports', to='authorizations.user')),
            ],
            options={
                'verbose_name': 'membership roster import',
                'verbose_name_plural': 'membership roster imports',
            },
        ),
    ]
