# Generated by Django 5.2.7 on 2026-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0014_membershiprosterimport_membershiprosterentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprosterentry',
            name='has_society_waiver',
            field=models.BooleanField(default=False),
        ),
    ]
