# Generated by Django 5.2.7 on 2026-03-09 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0015_membershiprosterentry_has_society_waiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('background_check', 'Background Check'), ('equestrian_waiver', 'Equestrian Event Waiver')], db_index=True, max_length=50)),
                ('jurisdiction', models.CharField(blank=True, choices=[('WA', 'Washington'), ('OR', 'Oregon'), ('ID', 'Idaho'), ('BC', 'British Columbia')], default='', max_length=2)),
                ('file', models.FileField(upload_to='supporting_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supporting document',
                'verbose_name_plural': 'supporting documents',
                'indexes': [models.Index(fields=['document_type', 'uploaded_at'], name='authorizati_documen_54cc2b_idx'), models.Index(fields=['review_status', 'uploaded_at'], name='authorizati_review__7917b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportingDocumentAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_document_links', to='authorizations.authorization')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_links', to='authorizations.supportingdocument')),
            ],
            options={
                'verbose_name': 'supporting document authorization link',
                'verbose_name_plural': 'supporting document authorization links',
            },
        ),
        migrations.CreateModel(
            name='SupportingDocumentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='authorizations.supportingdocument')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_document_links', to='authorizations.person')),
            ],
            options={
                'verbose_name': 'supporting document person link',
                'verbose_name_plural': 'supporting document person links',
            },
        ),
        migrations.AddConstraint(
            model_name='supportingdocument',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(document_type='background_check', jurisdiction='')
                    | models.Q(document_type='equestrian_waiver', jurisdiction__in=['WA', 'OR', 'ID', 'BC'])
                ),
                name='supporting_document_type_jurisdiction_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='supportingdocumentauthorization',
            constraint=models.UniqueConstraint(fields=('document', 'authorization'), name='unique_supporting_document_authorization_link'),
        ),
        migrations.AddConstraint(
            model_name='supportingdocumentperson',
            constraint=models.UniqueConstraint(fields=('document', 'person'), name='unique_supporting_document_person_link'),
        ),
    ]
