# Generated by Codex on 2026-03-09

from django.db import migrations


def create_status(apps, schema_editor):
    AuthorizationStatus = apps.get_model('authorizations', 'AuthorizationStatus')
    AuthorizationStatus.objects.get_or_create(name='Needs Kingdom Equestrian Waiver')


def noop_reverse(apps, schema_editor):
    # Keep historical data intact on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0016_supporting_documents'),
    ]

    operations = [
        migrations.RunPython(create_status, noop_reverse),
    ]
