# Generated by Django 5.2.7 on 2026-03-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0017_add_needs_kingdom_equestrian_waiver_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershiprosterentry',
            new_name='authorizati_members_28657a_idx',
            old_name='authorizati_membersh_75b202_idx',
        ),
        migrations.RenameIndex(
            model_name='sanction',
            new_name='authorizati_person__9f60b8_idx',
            old_name='authorizati_person__47768_idx',
        ),
        migrations.RenameIndex(
            model_name='sanction',
            new_name='authorizati_start_d_1641af_idx',
            old_name='authorizati_start_d_51bfb8_idx',
        ),
    ]
