# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0018_rename_authorizati_membersh_75b202_idx_authorizati_members_28657a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAuthorizationRecoveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('authorization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_recovery_entry', to='authorizations.authorization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_recovery_entries_created', to=settings.AUTH_USER_MODEL)),
                ('marshal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_recovery_marshal_entries', to='authorizations.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_recovery_entries', to='authorizations.person')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_recovery_entries', to='authorizations.weaponstyle')),
            ],
            options={
                'verbose_name': 'legacy authorization recovery entry',
                'verbose_name_plural': 'legacy authorization recovery entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='legacyauthorizationrecoveryentry',
            constraint=models.UniqueConstraint(fields=('person', 'style'), name='unique_legacy_recovery_person_style'),
        ),
    ]
