# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0019_legacyauthorizationrecoveryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='expiration',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='minor_on_paperwork',
            field=models.BooleanField(default=False),
        ),
    ]
