# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0020_legacy_recovery_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='concurring_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_recovery_concurring_officer_entries', to='authorizations.person'),
        ),
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='second_marshal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_recovery_second_marshal_entries', to='authorizations.person'),
        ),
    ]
