# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0021_legacy_recovery_marshal_signoffs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='legacyauthorizationrecoveryentry',
            name='unique_legacy_recovery_person_style',
        ),
        migrations.AlterField(
            model_name='legacyauthorizationrecoveryentry',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_recovery_entries', to='authorizations.authorization'),
        ),
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='previous_concurring_fighter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person'),
        ),
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='previous_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='previous_marshal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person'),
        ),
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.authorizationstatus'),
        ),
    ]
