# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0022_legacy_recovery_previous_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyauthorizationrecoveryentry',
            name='marshal_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
