# Generated by Django 5.2.7 on 2026-05-27 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0028_add_equestrian_authorization_officer_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('portal_adult_signature', 'Portal Adult Signature'), ('portal_minor_signature', 'Portal Minor Signature'), ('membership_roster', 'Membership Roster'), ('paper_waiver', 'Paper Waiver')], db_index=True, max_length=50)),
                ('waiver_type', models.CharField(choices=[('adult', 'Adult'), ('minor', 'Minor'), ('membership', 'Membership')], db_index=True, max_length=20)),
                ('signer_first_name', models.CharField(blank=True, default='', max_length=150)),
                ('signer_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('signer_relationship', models.CharField(blank=True, default='', max_length=50)),
                ('covered_first_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('covered_last_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('covered_sca_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('parent_first_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('parent_last_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('parent_sca_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('waiver_text', models.TextField(blank=True, default='')),
                ('waiver_version', models.CharField(blank=True, default='', max_length=50)),
                ('membership_number', models.CharField(blank=True, default='', max_length=20)),
                ('membership_expiration', models.DateField(blank=True, null=True)),
                ('paper_signed_date', models.DateField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, default='', max_length=1000)),
                ('note', models.TextField(blank=True, default='')),
                ('resulting_waiver_expiration', models.DateField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('signed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('covered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('roster_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_records', to='authorizations.membershiprosterimport')),
                ('signer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_records_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['covered_user', 'recorded_at'], name='authorizati_covered_6c30f6_idx'), models.Index(fields=['source', 'recorded_at'], name='authorizati_source_495ce4_idx')],
            },
        ),
    ]
