# Generated by Django 5.2.7 on 2026-05-27 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0031_repair_legacy_waiver_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Enter a valid postal code: 12345, 12345-6789, or A1A 1A1.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code (e.g., 12345, 12345-6789, or A1A 1A1).', regex='^(\\d{5}(-\\d{4})?|[A-Za-z]\\d[A-Za-z] ?\\d[A-Za-z]\\d)$')]),
        ),
    ]
