# Generated by Django 5.2.7 on 2026-05-29 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0034_rename_authorization_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('renewed', 'Renewed'), ('status_changed', 'Status changed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('marshal_changed', 'Marshal changed')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('before_expiration', models.DateField(blank=True, null=True)),
                ('after_expiration', models.DateField(blank=True, null=True)),
                ('after_concurring_fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person')),
                ('after_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('after_marshal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person')),
                ('after_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person')),
                ('after_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.authorizationstatus')),
                ('after_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.weaponstyle')),
                ('after_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='authorizations.authorization')),
                ('before_concurring_fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person')),
                ('before_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('before_marshal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person')),
                ('before_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.person')),
                ('before_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.authorizationstatus')),
                ('before_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authorizations.weaponstyle')),
                ('before_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_audit_entries', to='authorizations.person')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_audit_entries', to='authorizations.weaponstyle')),
            ],
            options={
                'verbose_name': 'authorization audit entry',
                'verbose_name_plural': 'authorization audit entries',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['authorization', 'changed_at'], name='authorizati_authori_c36979_idx'), models.Index(fields=['person', 'changed_at'], name='authorizati_person__9fd87f_idx'), models.Index(fields=['changed_by', 'changed_at'], name='authorizati_changed_5c82ab_idx'), models.Index(fields=['event_type', 'changed_at'], name='authorizati_event_t_c6b377_idx')],
            },
        ),
    ]
