# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [
        ('authorizations', '0036_add_seneschal_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationValidityInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('legacy_import', 'Legacy import'), ('portal_authorization', 'Portal authorization'), ('paper_entry', 'Paper entry'), ('membership_update', 'Membership update'), ('background_check_update', 'Background check update'), ('manual_repair', 'Manual repair')], db_index=True, max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_intervals', to='authorizations.authorization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_validity_intervals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'authorization validity interval',
                'verbose_name_plural': 'authorization validity intervals',
                'ordering': ['authorization_id', 'start_date', 'end_date'],
                'indexes': [
                    models.Index(fields=['authorization', 'start_date', 'end_date'], name='authorizati_authori_e78630_idx'),
                    models.Index(fields=['source', 'created_at'], name='authorizati_source_2a609b_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(condition=Q(('start_date__lte', F('end_date'))), name='auth_validity_interval_start_lte_end'),
                ],
            },
        ),
    ]
